name: tests

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Nightly job on default (main) branch
  schedule:
    - cron: '0 0 * * *'

jobs:
  # Pure Python testing
  python-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pushd pyrobosim && pip3 install . && popd
          setup/setup_pddlstream.bash
      - name: Run unit tests
        run: |
          pip3 install lark pytest pytest-html
          export PYTHONPATH=./dependencies/pddlstream:$PYTHONPATH
          test/run_tests.bash
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test/results/
        # Always publish test results even when there are failures.
        if: ${{ always() }}

  # Testing with ROS2
  ros2-foxy-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Docker image
        run: |
          export ROS_DISTRO=foxy
          docker/build_docker.bash
      - name: Run unit tests in Docker container
        run: |
          export ROS_DISTRO=foxy
          docker/run_docker.bash "src/pyrobosim/test/run_tests.bash" ci_mode
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-foxy
          path: test/results/
        # Always publish test results even when there are failures.
        if: ${{ always() }}

  ros2-humble-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Docker image
        run: |
          export ROS_DISTRO=humble
          docker/build_docker.bash
      - name: Run unit tests in Docker container
        run: |
          export ROS_DISTRO=humble
          docker/run_docker.bash "src/pyrobosim/test/run_tests.bash" ci_mode
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-humble
          path: test/results/
        # Always publish test results even when there are failures.
        if: ${{ always() }}
